path_to_key = "~/aws/ssh_main_key.pem"
path_to_ngix_repo = "~/aws/repo/nginx.repo"
path_to_jenkins_repo = "~/aws/repo/jenkins.repo"
path_to_jenkins_conf = "~/aws/tpl/jenkins.conf.tpl"
path_to_nginx_conf = "~/aws/tpl/nginx.conf.tpl"
path_to_rundeck_service = "~/aws/tpl/rundeck.service.tpl"
rundeck_version = "3.1.3-20191204"
