#!/usr/bin/env groovy
node {
    label 'dockerslave'
    
    stage('HelloWorld'){
        echo 'test'
    }
    stage('test terraform'){
        sh 'terraform --version'
    }
    stage('get Git repo'){
        git credentialsId: 'git_devops', url: 'git@github.com:alvin-dp/DevOps.git'
    }
    stage('list Local Repo'){
        sh 'ls -la'
    }    
    stage('terraform init&plan'){
        withCredentials([string(credentialsId: 'a38c6528-d489-41e7-865b-8cb175ec5f8a', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'f0377c4e-46f2-400f-b3cd-f3f6bbdeae7a', variable: 'AWS_SECRET_ACCESS_KEY')]) {
            sh 'cd single_terraform_machine && terraform init && terraform plan'
            }
    }
}