node('dockerslaveTF'){
    tool name: 'maven', type: 'maven'
    stage('test install') {
        withEnv(["PATH=${env.PATH}:${tool 'maven'}/bin"]){
            sh 'env | grep PATH'
            sh 'mvn -v'
    }
    }
    stage('Get app from Repo') {
            git credentialsId: 'git_devops', url: 'git@github.com:alvin-dp/simple-java-maven-app.git'
    }
    stage('list WorkDir') {
            sh 'ls -la'
    }                         
    stage('Build') {
        withEnv(["PATH=${env.PATH}:${tool 'maven'}/bin"]){
        sh 'mvn -B -DskipTests clean package'
        }
  }
  stage('Test') {
      withEnv(["PATH=${env.PATH}:${tool 'maven'}/bin"]){
      sh 'mvn test'
      sh 'ls -la'
      stash includes: 'target/*.jar', name: 'artiApp'
      }
  }
}
node('dockerslaveTF'){
    tool name: 'tool_docker'
    stage('test install') {
        withEnv(["PATH=${env.PATH}:${tool 'tool_docker'}/bin"]){
        sh 'docker -v'
        }
    } 
    stage('unstash for deploy') {
        unstash 'artiApp'
        // withEnv(["PATH=${env.PATH}:${tool 'tool_docker'}/bin"]){
        // sh 'docker -v'
        // }
        sh 'ls -la'
    }    
}